import { Game } from "../types/gameType.js";

const actionId = "69e2015a82b0d22d9432f159";
const puzzleId = "69e203e53b8bd3e32f6c53b6";
const sandboxId = "69e203e53b8bd3e32f6c53b7";
const survivalId = "69e203e53b8bd3e32f6c53b8";
const actionAdventureId = "69e203e53b8bd3e32f6c53b9";
const sportsId = "69e203e53b8bd3e32f6c53ba";
const racingid = "69e203e53b8bd3e32f6c53bb";
const battleRoyaleId = "69e203e53b8bd3e32f6c53bc";
const shooterId = "69e203e53b8bd3e32f6c53bd";
const adventureId = "69e203e53b8bd3e32f6c53bf";
const rpgId = "69e203e53b8bd3e32f6c53c0";
const openWorldId = "69e203e53b8bd3e32f6c53c1";
const platformId = "69e203e53b8bd3e32f6c53c2";
const mmorpgId = "69e203e53b8bd3e32f6c53c3";
const mobaId = "69e203e53b8bd3e32f6c53c4";
const actionRpgId = "69e203e53b8bd3e32f6c53c6";
const simulationId = "69e203e53b8bd3e32f6c53c7";
const horrorId = "69e203e53b8bd3e32f6c53c8";
const fightingId = "69e203e53b8bd3e32f6c53c9";

export const games: Game[] = [
  {
    title: "Tetris",
    release: new Date("1988-06-06"),
    dev: "Alexey Pajitnov",
    genres: ["Puzzle"],
    platforms: ["Multi"],
    desc: "Timeless tile-matching puzzle game.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Minecraft",
    release: new Date("2011-11-18"),
    dev: "Mojang Studios",
    genres: ["Sandbox", "Survival"],
    platforms: ["Multi"],
    desc: "Open-world creative building and survival.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Grand Theft Auto V",
    release: new Date("2013-09-17"),
    dev: "Rockstar North",
    genres: ["Action-adventure"],
    platforms: ["Multi"],
    desc: "Open-world action with story and online modes.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Wii Sports",
    release: new Date("2006-11-19"),
    dev: "Nintendo EAD",
    genres: ["Sports"],
    platforms: ["Wii"],
    desc: "Collection of sports minigames.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Red Dead Redemption 2",
    release: new Date("2018-10-26"),
    dev: "Rockstar Games",
    genres: ["Action-adventure"],
    platforms: ["PS4", "Xbox One", "PC"],
    desc: "Western open-world story.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Mario Kart 8 Deluxe",
    release: new Date("2017-04-28"),
    dev: "Nintendo EPD",
    genres: ["Racing"],
    platforms: ["Switch"],
    desc: "Kart racing with characters from Mario.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "PUBG: Battlegrounds",
    release: new Date("2017-12-20"),
    dev: "PUBG Studios",
    genres: ["Battle Royale", "Shooter"],
    platforms: ["PC", "Console"],
    desc: "Battle royale shooter.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Terraria",
    release: new Date("2011-05-16"),
    dev: "Re-Logic",
    genres: ["Action", "Adventure"],
    platforms: ["Multi"],
    desc: "2D sandbox exploration.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "The Witcher 3: Wild Hunt",
    release: new Date("2015-05-19"),
    dev: "CD Projekt Red",
    genres: ["RPG", "Open World"],
    platforms: ["Multi"],
    desc: "Story-driven open-world fantasy RPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Call of Duty: Modern Warfare",
    release: new Date("2019-10-25"),
    dev: "Infinity Ward",
    genres: ["Shooter"],
    platforms: ["Multi"],
    desc: "Modern military shooter.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Fortnite",
    release: new Date("2017-07-21"),
    dev: "Epic Games",
    genres: ["Battle Royale", "Shooter"],
    platforms: ["Multi"],
    desc: "Online shooter with building mechanics.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "The Elder Scrolls V: Skyrim",
    release: new Date("2011-11-11"),
    dev: "Bethesda Game Studios",
    genres: ["RPG", "Action"],
    platforms: ["Multi"],
    desc: "Open-world fantasy questing.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Super Mario Odyssey",
    release: new Date("2017-10-27"),
    dev: "Nintendo EPD",
    genres: ["Platform", "Adventure"],
    platforms: ["Switch"],
    desc: "Mario explores to save Peach.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "The Legend of Zelda: Breath of the Wild",
    release: new Date("2017-03-03"),
    dev: "Nintendo EPD",
    genres: ["Action-adventure"],
    platforms: ["Switch", "Wii U"],
    desc: "Open-world adventure.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "World of Warcraft",
    release: new Date("2004-11-23"),
    dev: "Blizzard Entertainment",
    genres: ["MMORPG"],
    platforms: ["PC"],
    desc: "Massively multiplayer fantasy RPG.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "League of Legends",
    release: new Date("2009-10-27"),
    dev: "Riot Games",
    genres: ["MOBA"],
    platforms: ["PC"],
    desc: "Competitive team strategy game.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Counter-Strike: Global Offensive",
    release: new Date("2012-08-21"),
    dev: "Valve",
    genres: ["Shooter"],
    platforms: ["PC"],
    desc: "Tactical team shooter.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Starfield",
    release: new Date("2023-09-06"),
    dev: "Bethesda Game Studios",
    genres: ["Action RPG"],
    platforms: ["PC", "Xbox Series X/S", "PS5"],
    desc: "Open-world space RPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Baldur's Gate 3",
    release: new Date("2023-08-03"),
    dev: "Larian Studios",
    genres: ["RPG"],
    platforms: ["Multi"],
    desc: "Fantasy role-playing adventure.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Horizon Zero Dawn",
    release: new Date("2017-02-28"),
    dev: "Guerrilla Games",
    genres: ["Action RPG"],
    platforms: ["PS4", "PC", "PS5"],
    desc: "Post-apocalyptic action RPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Halo: Combat Evolved",
    release: new Date("2001-11-15"),
    dev: "Bungie",
    genres: ["Shooter"],
    platforms: ["Xbox", "PC"],
    desc: "Sci-fi first-person shooter.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "BioShock",
    release: new Date("2007-08-21"),
    dev: "Irrational Games",
    genres: ["Shooter", "Adventure"],
    platforms: ["Multi"],
    desc: "Atmospheric underwater FPS.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Mass Effect 2",
    release: new Date("2010-01-26"),
    dev: "BioWare",
    genres: ["RPG", "Shooter"],
    platforms: ["Multi"],
    desc: "Sci-fi RPG with choice-driven story.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Portal 2",
    release: new Date("2011-04-19"),
    dev: "Valve",
    genres: ["Puzzle", "Action"],
    platforms: ["Multi"],
    desc: "Physics-based puzzle game.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Elden Ring",
    release: new Date("2022-02-25"),
    dev: "FromSoftware",
    genres: ["Action RPG"],
    platforms: ["Multi"],
    desc: "Open-world dark fantasy RPG.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "God of War Ragnarök",
    release: new Date("2022-11-09"),
    dev: "Santa Monica Studio",
    genres: ["Action", "Adventure"],
    platforms: ["PS4", "PS5"],
    desc: "Norse myth action adventure.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Assassin's Creed Valhalla",
    release: new Date("2020-11-10"),
    dev: "Ubisoft Montreal",
    genres: ["Action-adventure"],
    platforms: ["Multi"],
    desc: "Viking-era open-world adventure.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Overwatch",
    release: new Date("2016-05-24"),
    dev: "Blizzard Entertainment",
    genres: ["Shooter"],
    platforms: ["Multi"],
    desc: "Team-based multiplayer shooter.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Rocket League",
    release: new Date("2015-07-07"),
    dev: "Psyonix",
    genres: ["Sports", "Racing"],
    platforms: ["Multi"],
    desc: "Soccer with cars.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Cyberpunk 2077",
    release: new Date("2020-12-10"),
    dev: "CD Projekt Red",
    genres: ["Action RPG"],
    platforms: ["Multi"],
    desc: "Futuristic open-world RPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Animal Crossing: New Horizons",
    release: new Date("2020-03-20"),
    dev: "Nintendo",
    genres: ["Simulation"],
    platforms: ["Switch"],
    desc: "Relaxing life simulation.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Dead Space",
    release: new Date("2008-10-14"),
    dev: "EA Redwood Shores",
    genres: ["Horror", "Shooter"],
    platforms: ["Multi"],
    desc: "Sci-fi horror survival.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Final Fantasy VII Remake",
    release: new Date("2020-04-10"),
    dev: "Square Enix",
    genres: ["RPG"],
    platforms: ["PS4", "PS5"],
    desc: "Modern reimagining of classic JRPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Doom Eternal",
    release: new Date("2020-03-20"),
    dev: "id Software",
    genres: ["Shooter"],
    platforms: ["Multi"],
    desc: "Fast-paced demon combat.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Resident Evil 4 Remake",
    release: new Date("2023-03-24"),
    dev: "Capcom",
    genres: ["Horror", "Shooter"],
    platforms: ["Multi"],
    desc: "Updated survival horror shooter.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Sekiro: Shadows Die Twice",
    release: new Date("2019-03-22"),
    dev: "FromSoftware",
    genres: ["Action"],
    platforms: ["Multi"],
    desc: "Challenging samurai adventure.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Persona 5 Royal",
    release: new Date("2020-03-31"),
    dev: "Atlus",
    genres: ["RPG"],
    platforms: ["Multi"],
    desc: "Stylish turn-based RPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Street Fighter V",
    release: new Date("2016-02-16"),
    dev: "Capcom",
    genres: ["Fighting"],
    platforms: ["Multi"],
    desc: "Competitive fighting game.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Forza Horizon 5",
    release: new Date("2021-11-05"),
    dev: "Playground Games",
    genres: ["Racing"],
    platforms: ["Multi"],
    desc: "Open-world racing.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Dragon Age: Inquisition",
    release: new Date("2014-11-18"),
    dev: "BioWare",
    genres: ["RPG"],
    platforms: ["Multi"],
    desc: "Epic fantasy RPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Splatoon 3",
    release: new Date("2022-09-09"),
    dev: "Nintendo EPD",
    genres: ["Shooter"],
    platforms: ["Switch"],
    desc: "Color-splattering team shooter.",
    thumb: "",
    multiplayer: true,
    avg_rating: 0,
    review: [],
  },
  {
    title: "The Last of Us Part II",
    release: new Date("2020-06-19"),
    dev: "Naughty Dog",
    genres: ["Action", "Adventure"],
    platforms: ["PS4"],
    desc: "Post-apocalyptic narrative action.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Metroid Dread",
    release: new Date("2021-10-08"),
    dev: "MercurySteam",
    genres: ["Action", "Adventure"],
    platforms: ["Switch"],
    desc: "2D Metroidvania action.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
  {
    title: "Star Wars Jedi: Fallen Order",
    release: new Date("2019-11-15"),
    dev: "Respawn Entertainment",
    genres: ["Action", "Adventure"],
    platforms: ["Multi"],
    desc: "Single-player Star Wars action RPG.",
    thumb: "",
    multiplayer: false,
    avg_rating: 0,
    review: [],
  },
];
