### Alla spel
GET http://localhost:3000/api/games

### Sök på titel
GET http://localhost:3000/api/games?title=zelda

### Kombinerad sökning
GET http://localhost:3000/api/games?genre=horror&multiplayer:true

### Radera spel via Id

DELETE http://localhost:3000/api/games/69d6a891c45137184e82080

### Lägg till spel

POST http://localhost:3000/api/games
Content-Type: application/json

{
    "title": "Mimesis",
    "created": 2025,
    "dev": "idk",
    "genre": "Horror",
    "multiplayer": true
}

### Test global errorMiddleware (invalid ObjectId)
DELETE http://localhost:3000/api/games/not-a-valid-id