### Logga in
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

### Alla spel
GET http://localhost:3000/api/games

### Sök på titel
GET http://localhost:3000/api/games?title=zelda

### Sök på id
GET http://localhost:3000/api/games/69cd701066f8103d510cc599

### Kombinerad sökning
GET http://localhost:3000/api/games?genre=horror&multiplayer=true

### Radera spel via Id
DELETE http://localhost:3000/api/games/69d6a891c45137184e82080

### Lägg till spel
POST http://localhost:3000/api/games
Content-Type: application/json

{
  "title": "Mimesis",
  "release": "2025-01-01",
  "dev": "idk",
  "genres": ["Horror"],
  "platforms": ["PC"],
  "multiplayer": true
}

### Test global errorMiddleware (invalid ObjectId)
DELETE http://localhost:3000/api/games/not-a-valid-id

### Uppdatera spel
PATCH http://localhost:3000/api/games/69d78e8184d39f9da87e7800
Content-Type: application/json

{
  "title": "L4D2",
  "genres": ["Action"],
  "multiplayer": true
}

### Lägg till spel i bibliotek
POST http://localhost:3000/api/library
Content-Type: application/json

{
  "gameId": "69e62b5d8f1d9f73f49a1fcc"
}

### Hämta bibliotek
GET http://localhost:3000/api/library

### Uppdatera speltid
PATCH http://localhost:3000/api/library/69e622f0e28b137e4d237d1e
Content-Type: application/json

{
  "playtimeMinutes": 120
}

### Ta bort spel från bibliotek
DELETE http://localhost:3000/api/library/69e62b5d8f1d9f73f49a1fcc